### ISSUE TITLE
Issue with IRIX

### ISSUE THREAD

**Issue by dillera** [drj11/xwd2png#3]
Hello  - trying to use this to capture some x screenshots on irix but I'm getting an error:

```
dillera@fuel ~ $ xwd -root | xwd.py
Traceback (most recent call last):
  File "/usr/people/dillera/.local/bin/xwd.py", line 309, in <module>
    main()
  File "/usr/people/dillera/.local/bin/xwd.py", line 283, in main
    format = xwd.uni_format()
  File "/usr/people/dillera/.local/bin/xwd.py", line 69, in uni_format
    "Cannot handle visual_class {!r}".format(self.visual_class)
__main__.NotImplemented: Cannot handle visual_class 5
dillera@fuel ~ $ 
```

Any idea what visual_class 5 is?

**Comment by drj11** [comment]
Migrated to https://codeberg.org/drj/xwd2png/issues/3 (i am moving this project off github)
